server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: bootsecurity
    key-store-type: PKCS12
    key-alias: bootsecurity
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytube?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: mytube
    password: bitc5600
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 2400546060259431
            client-secret: 228f46dbbfdd948aebdf5ee8c6cf49b8
            scope:
            - email
            - public_profile

          google: 
            client-id: 73269684248-pssn027f5441bhcg9cerhaqso72qpgtt.apps.googleusercontent.com
            client-secret: _w5bBcEzyew32Fk8lzza_3iH
            scope: 
            - email
            - profile
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
        
          
